# Generated by Django 5.2.7 on 2025-11-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
